language: python

dist: xenial

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy2.7-6.0

env:
    - KAFKA_VERSION=1.1.0

addons:
  apt:
    packages:
      - libsnappy-dev
      - openjdk-8-jdk

cache:
  directories:
    - $HOME/.cache/pip
    - servers/

before_install:
    - source travis_java_install.sh
    - ./build_integration.sh

install:
    - pip install tox coveralls
    - pip install .

script:
    - tox -i https://pypi.python.org/simple -e `if [ "$TRAVIS_PYTHON_VERSION" == "pypy2.7-6.0" ]; then echo pypy; else echo py${TRAVIS_PYTHON_VERSION/./}; fi`

after_success:
  - coveralls
